---
- name: "extract the zipped artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "start the app"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
